services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: >
      sh -c "poetry run alembic upgrade head && poetry run uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - task_data:/var/lib/postgresql

volumes:
  task_data: