"""Refactored users roles and added secondary for users_tasks

Revision ID: fc174a6adcdf
Revises: 6b4fa79683a3
Create Date: 2025-08-09 23:07:14.868543

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc174a6adcdf"
down_revision: Union[str, Sequence[str], None] = "6b4fa79683a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users ALTER COLUMN roles TYPE json USING roles::json")
    op.alter_column("users", "roles", existing_type=sa.VARCHAR(), type_=sa.JSON(), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users ALTER COLUMN roles TYPE varchar(255) USING roles::varchar(255)")
    op.alter_column("users", "roles", existing_type=sa.JSON(), type_=sa.VARCHAR(), existing_nullable=False)
    # ### end Alembic commands ###
